### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/os/VibrationEffect

### ISSUE THREAD

**Issue by psa-jforestier** [j-jorge/bim#2]
Installed version : v2
Android : version 7.1.1 ; sdk 25 ; Sony Xperia Z5 compact; Physical size: 720x1280 ; Physical density: 320 ;Override density: 360

Quand je lance le jeu, j'ai tout de suite une erreur "Bim! a cesser de fonctionner".

Logcat indique : 
```
adb shell pidof -s bim.app
25884
adb logcat --pid=25884
09-26 14:22:23.123 25884 25884 I art     : Starting a blocking GC AddRemoveAppImageSpace
09-26 14:22:23.262 25884 25884 D AxmolEngine: android version is 25, isSupportLowLatency: true
(...)
09-26 14:22:23.290 25884 25884 E AndroidRuntime: FATAL EXCEPTION: main
09-26 14:22:23.290 25884 25884 E AndroidRuntime: Process: bim.app, PID: 25884
09-26 14:22:23.290 25884 25884 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/os/VibrationEffect;
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at androidx.media3.exoplayer.mediacodec.b0.b(SourceFile:1)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at iscool.system.HapticFeedbackService.init(SourceFile)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at iscool.system.SystemService.init(SourceFile)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at bim.app.AppActivity.onCreate(SourceFile)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6720)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2673)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:241)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6274)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
09-26 14:22:23.290 25884 25884 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.VibrationEffect" on path: DexPathList[[zip file "/data/app/bim.app-1/base.apk"],nativeLibraryDirectories=[/data/app/bim.app-1/lib/arm64, /data/app/bim.app-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-26 14:22:23.290 25884 25884 E AndroidRuntime:        ... 16 more
```

**Comment by j-jorge** [comment]
Salut, je m'étais planté en uploadant l'apk. Peux-tu tester avec [celui-ci](https://github.com/j-jorge/bim/releases/download/v2/bim-2.apk) (j'ai remplacé celui de la page des releases).
